// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKGRxRDUfhFBi3Xh8uI8j7TpAHNxp-lxI',
    appId: '1:48466955422:web:68448c2ff82b162440bf8f',
    messagingSenderId: '48466955422',
    projectId: 'all-authentication-c1f4b',
    authDomain: 'all-authentication-c1f4b.firebaseapp.com',
    storageBucket: 'all-authentication-c1f4b.appspot.com',
    measurementId: 'G-Y0JZWXG1KB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIceu3BZmoedHvsh4n5z6DRcJL_45UGGA',
    appId: '1:48466955422:android:5c4926c303a2220d40bf8f',
    messagingSenderId: '48466955422',
    projectId: 'all-authentication-c1f4b',
    storageBucket: 'all-authentication-c1f4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRQeIOa7Hsd9mgidapcH1ZEgBdCGGPxUg',
    appId: '1:48466955422:ios:9bc2ebe2eefb4e8940bf8f',
    messagingSenderId: '48466955422',
    projectId: 'all-authentication-c1f4b',
    storageBucket: 'all-authentication-c1f4b.appspot.com',
    iosBundleId: 'com.example.authentication',
  );
}
